/*
 * @FilePath: \AceSix.github.io\static_cv\js\my_exp.js
 * @Author: AceSix
 * @Date: 2021-06-30 16:53:31
 * @LastEditors: Ziang Liu
 * @LastEditTime: 2021-07-01 11:26:48
 * Copyright (C) 2021 SJTU. All rights reserved.
 */
var i = "./static_cv/img/";
my_experiences = [{
        id: "2016_10",
        name: "Coding",
        cname: "编程",
        time: ["2016-10", "now"],
        tags: ["skill"],
        img: i + "",
        link: "",
        cdesc: "熟悉python,C++,javascript，C和java也写过一点点",
    },
    {
        id: "2017_8",
        name: "English",
        cname: "英语",
        time: ["2016-10", "now"],
        tags: ["skill"],
        img: i + "",
        link: "",
        cdesc: "TOEFL 107，GRE 323，而且我是不需要复习的^_^",
    },
    {
        id: "2018_9",
        name: "Nav&Sens Lab",
        cname: "感知导航实验室实习",
        time: ["2018-6", "2019-8"],
        tags: ["research"],
        link: "",
        img: i + "lab_memo.jpg",
        cdesc: "开始学习SLAM、定位导航、系统控制",
    },
    {
        id: "2018_11",
        name: "Front-end",
        cname: "前端开发",
        time: ["2018-04", "now"],
        tags: ["skill"],
        img: i + "",
        link: "",
        cdesc: "PyQt, Vue, Electron都尝试过了，网络编程也还好",
    },
    {
        id: "2019_1",
        name: "3D modeling",
        cname: "3D 建模",
        time: ["2019-05", "2019-06"],
        tags: ["skill"],
        img: i + "model3d.jpg",
        link: "",
        cdesc: "算是比较有用的技能吧，但是并没有做出更复杂的东西",
    },
    {
        id: "2019_2",
        name: "Badminton",
        cname: "羽毛球",
        time: ["2017-09", "now"],
        tags: ["life"],
        img: i + "",
        link: "",
        cdesc: "随着学院拿了两届亚军，也是会打一点啦",
    },
    {
        id: "2019_3",
        name: "blowing robot",
        cname: "吹笛机器人",
        time: ["2019-01", "2019-06"],
        tags: ["project"],
        img: i + "blower.jpg",
        link: "",
        cdesc: "系统设计的实践，遗憾的是忽略了气泵的噪音比笛子声音更大",
    },
    {
        id: "2019_8",
        name: "French",
        cname: "法语",
        time: ["2018-12", "2020-05"],
        tags: ["skill"],
        img: i + "",
        link: "",
        cdesc: "差不多只会回答Oui/Non的水平吧...",
    },
    {
        id: "2019_9",
        name: "CV Lab",
        cname: "图像所实习",
        time: ["2019-9", "now"],
        tags: ["research"],
        link: "",
        img: i + "image.png",
        cdesc: "进入图像所，开始学习深度学习、图像生成",
    },
    {
        id: "2019_11",
        name: "Testbed Paper",
        cname: "传感器平台发表",
        time: ["2019-8", "2019-12"],
        tags: ["publication"],
        link: "https://ieeexplore.ieee.org/document/8702610",
        img: i + "testbed.png",
        cdesc: "ISCAS2019, Design of a reconfigurable multi-sensor testbed for autonomous vehicles and ground robots",
    },
    {
        id: "2020_2",
        name: "Back-end",
        cname: "后端开发",
        time: ["2019-01", "now"],
        tags: ["skill"],
        img: i + "",
        link: "",
        cdesc: "入门级别的软件设计，能独立承担深度学习算法的研究，有idea但经常不work",
    },
    {
        id: "2020_5",
        name: "CooGAN",
        cname: "CooGAN",
        tags: ["publication"],
        time: ["2019-11", "2020-5"],
        img: i + "Coogan.png",
        link: "http://hotu.co/blog/color/2_color_palette.html",
        cdesc: "ECCV2020, CooGAN: A Memory-Efficient Framework for High-Resolution Facial Attribute Editing",
    },
    {
        id: "2020_6",
        name: "Graduation from SJTU",
        cname: "上海交大，毕业",
        time: ["2016-8", "2020-06"],
        tags: ['degree'],
        link: "",
        img: i + "sjtu.jpg",
        cdesc: "机械工程试点班，工学学士；法语语言学，文学学士",
    },
    {
        id: "2021_4",
        name: "coffee trip",
        cname: "咖啡之旅",
        time: ["2021-04", "now"],
        tags: ["life"],
        img: i + "coffee.png",
        link: "",
        cdesc: "开始尝试世上各种咖啡",
    },
    {
        id: "2021_5",
        name: "FOTAST",
        cname: "FOTAST",
        time: ["2021-3", "2021-6"],
        tags: ["publication"],
        img: i + "fost.png",
        link: "https://link.springer.com/chapter/10.1007/978-3-030-67832-6_4",
        cdesc: "MMM2021, Fast Optimal Transport Artistic Style Transfer",
    },
    {
        id: "2021_7",
        name: "Brown",
        cname: "布朗",
        time: ["2021-7", "?"],
        tags: ["degree"],
        img: i + "",
        link: "",
        cdesc: "Gap一年了，快让我过去吧...",
    },
];