/*
 * @FilePath: \AceSix.github.io\static_cv\js\my_exp.js
 * @Author: AceSix
 * @Date: 2021-06-30 16:53:31
 * @LastEditors: AceSix
 * @LastEditTime: 2021-06-30 16:53:40
 * Copyright (C) 2021 SJTU. All rights reserved.
 */
var i = "./img/";
my_experiences = [
    {
        id: "2011_7",
        name: "Bike Travel",
        cname: "单车旅行",
        time: ["2005-10", "2013-08"],
        tags: [],
        link: "http://bbs.8264.com/thread-1237199-1-1.html",
        img: i + "Bike-Travel.jpg",
        cdesc: "热爱骑行，走过中国20余省, 7入藏区, 30000多公里 <br> 上海新闻晚报旅行专栏作者, 旅行杂志摄影供稿",
    },
    {
        id: "2010_1",
        name: "Circle Rank",
        cname: "圆形实验",
        time: ["2010-10", "2010-10"],
        tags: ["simple", "mobile"],
        link: "http://hotu.co/cv/demos/circle/",
        img: i + "Circle-Rank.jpg",
        cdesc: "通过函数排列圆形、控制颜色，形成复杂的形态<br>(改自原processing文件)<br>",
    },
    {
        id: "2010_2",
        name: "L-system",
        cname: "树形实验",
        time: ["2010-11", "2010-11"],
        tags: ["simple", "mobile"],
        link: "http://hotu.co/cv/demos/tree/",
        img: i + "L-system.jpg",
        cdesc: "改写L-Syestem, 形成一种有意思的生物形态实验 <br>(改自原processing文件)<br>",
    },
    {
        id: "2013_1",
        name: "Color Analysis",
        cname: "色彩分析",
        time: ["2013-10", "2013-10"],
        tags: ["webgl", "research"],
        link: "http://color3d.herokuapp.com/",
        img: i + "Color Analysis.jpg",
        cdesc: "	    某种意义上，图片就是一堆像素，<br>我们可以通过这个工具查看一张图片或对比两张图片<br>在HSL/RGB/LAB等色彩空间的分布<br>	    ",
    },
    {
        id: "2013_2",
        name: "Color Analysis-2",
        cname: "色彩分析2",
        tags: ["research"],
        time: ["2013-10", "2013-10"],
        img: i + "Color-Analysis-2.jpg",
        link: "http://hotu.co/blog/color/2_color_palette.html",
        cdesc: "探索色彩分布规律，并用在可视化实践里",
    },
    {
        id: "2013_2",
        name: "AliEye",
        cname: "阿里眼",
        time: ["2013-09", "2013-11"],
        tags: ["alibaba", "webgl", "map"],
        img: i + "AliEye.jpg",
        link: "http://www.tudou.com/programs/view/Rxg-S-_98K0/",
        cdesc: "阿里巴巴内部展示<br> 多场景任意排列次序，流畅动画衔接, <br>公关部微博、贵州电台等报道",
    },
    {
        id: "2014_1",
        name: "Open Wedding",
        cname: "全世界求婚",
        time: ["2014-05", "2014-06"],
        tags: ["webgl", "map"],
        img: i + "Open-Wedding.jpg",
        link: "http://www.hotu.co/wedding/",
        cdesc: "求婚h5网站<br>通过朋友以及众筹，邀请世界各地的朋友拍照<br> 应用，从图片生成视频<br>",
    },
    {
        id: "2015_1",
        name: "CEBIT Exhibition",
        cname: "CEBIT 国际展会",
        time: ["2015-01", "2015-03"],
        tags: ["webgl", "alibaba", "major", "map"],
        img: i + "CEBIT-Exhibition.jpg",
        link: "http://www.tudou.com/programs/view/FaZUFOeZFw0/",
        cdesc: "公司项目,负责前端架构<br>马云在CEBIT大会通过大屏<br>向中德两国总理介绍阿里业务<br>",
    },
    {
        id: "2015_2",
        name: "Sound Viz",
        cname: "声音可视化",
        time: ["2015-08", "2015-09"],
        tags: ["webgl", "simple"],
        img: i + "Sound-Viz.jpg",
        link: "http://hotu.co/cv/demos/soundviz/",
        cdesc: "基于fft的声音可视化<br>低音 -> 冷色，粗钝的形态<br> 高音 -> 暖色、锋利的形态",
    },
    {
        id: "2015_3",
        name: "Hotu Painter",
        cname: "糊涂画板",
        tags: ["mobile", "major"],
        time: ["2015-03", "2015-09"],
        link: "http://hotu.co/hua/",
        img: i + "hotu.jpg",
        cdesc: "支持pc/pad/手机的画板<br>",
    },
    {
        id: "2015_9",
        name: "House Price",
        cname: "上海房价",
        img: i + "House-Price.jpg",
        tags: ["spider", "map"],
        time: ["2015-09", "2015-09"],
        cdesc: "根据爬取的数据，从销量、价格等维度<br>分析上海的租售情况",
    },
    {
        id: "2015_11",
        name: "Double 11(2015)",
        cname: "双十一(2015)",
        tags: ["alibaba", "major", "map"],
        time: ["2015-09", "2015-11"],
        img: i + "Double-11(2015).jpg",
        link: "http://www.dtcj.com/news/5640023f695a326f96fe0100",
        cdesc: "2015年水立方媒体接待大厅数据可视化",
    },
    {
        id: "2015_122",
        name: "Explore Password",
        cname: "密码漫游记",
        tags: ["research"],
        time: ["2015-11", "2015-11"],
        img: i + "Explore-Password.jpg",
        link: "http://hotu.co/blog/spider/mima.html",
    },
    {
        id: "2016_1.1",
        name: "Spider Man",
        cname: "爬虫框架",
        time: ["2016-01", "2015-01"],
        tags: ["spider"],
        img: i + "Spider-Man.jpg",
        link: "https://github.com/zhouningyi/spider_man/",
    },
    {
        id: "2016_01",
        name: "GPU Physics",
        cname: "GPU 物理",
        isalibaba: !1,
        tags: [],
        time: ["2016-01", "2016-01"],
        cdesc: "通过GPU模拟物体互相作用计算<br>可达每秒数十亿次计算",
    },
];