/*
 * @FilePath: \AceSix.github.io\static_cv\js\my_exp.js
 * @Author: AceSix
 * @Date: 2021-06-30 16:53:31
 * @LastEditors: AceSix
 * @LastEditTime: 2024-09-27 22:55:43
 * Copyright (C) 2021 SJTU. All rights reserved.
 */
var i = "./static_cv/img/";
my_experiences = [{
        id: "2016_10",
        name: "Coding",
        cname: "编程",
        time: ["2016-10", "now"],
        tags: ["skill"],
        img: i + "coding.png",
        link: "",
        desc: "Quite familiar with python, C++ and JavaScript. Also worked with C and Java.",
        cdesc: "熟悉python,C++,javascript，C和java也写过一点点",
    },
    {
        id: "2017_8",
        name: "English",
        cname: "英语",
        time: ["2016-10", "now"],
        tags: ["skill"],
        img: i + "",
        link: "",
        desc: "Working on it :)",
        cdesc: "Working on it :)",
    },
    {
        id: "2017_10",
        name: "Cat",
        cname: "猫党",
        time: ["2017-10", "now"],
        tags: ["life"],
        img: i + "cat.jpg",
        link: "",
        desc: "How to pet a wild cat",
        cdesc: "How to pet a wild cat",
    },
    // {
    //     id: "2018_9",
    //     name: "Nav&Sens Lab",
    //     cname: "感知导航实验室实习",
    //     time: ["2018-6", "2019-8"],
    //     tags: ["research"],
    //     link: "",
    //     img: i + "lab_memo.jpg",
    //     desc: "SLAM related researches in Nav&Sens Lab, SJTU. My work included the design of a \
    //             SLAM testbed and exploring a federal Kalman filter algorithm in solely global frame.",
    //     cdesc: "开始学习SLAM、定位导航、系统控制",
    // },
    // {
    //     id: "2018_11",
    //     name: "Front-end",
    //     cname: "前端开发",
    //     time: ["2018-04", "now"],
    //     tags: ["skill"],
    //     img: i + "",
    //     link: "",
    //     desc: "My front-end programming starts from data visualization. I got most of my experience creating \
    //                 UI interfaces in my undergrad dissertation advisor's team. ",
    //     cdesc: "PyQt, Vue, Electron都尝试过了，网络编程也还好",
    // },
    {
        id: "2019_1",
        name: "3D modeling",
        cname: "3D 建模",
        time: ["2019-05", "2019-06"],
        tags: ["skill"],
        img: i + "model3d.jpg",
        link: "",
        desc: "Quite helpful in testbed design at Nav&Sens Lab. But I didn't go too deep in this ares.",
        cdesc: "算是比较有用的技能吧，但是并没有做出更复杂的东西",
    },
    {
        id: "2019_2",
        name: "Badminton",
        cname: "羽毛球",
        time: ["2017-09", "now"],
        tags: ["life"],
        img: i + "",
        link: "",
        desc: "Two time 2nd place in SJTU's team competition. Do it mostly for fun :)",
        cdesc: "随着学院拿了两届亚军，也是会打一点啦",
    },
    {
        id: "2019_3",
        name: "flute blowing robot",
        cname: "吹笛机器人",
        time: ["2019-01", "2019-06"],
        tags: ["project"],
        img: i + "blower.jpg",
        link: "",
        desc: "One interesting course project. We use one air pump for blowing and simulate fingertip with the combination of\
            several common items. Too bad the air pump is louder than the flute >_<",
        cdesc: "系统设计的实践，遗憾的是忽略了气泵的噪音比笛子声音更大",
    },
    {
        id: "2021_12",
        name: "Godray under sea.",
        cname: "深海模拟器",
        time: ["2021-10", "2021-12"],
        tags: ["project"],
        img: i + "undersea.png",
        link: "",
        desc: "A real-time rendering project with Qt and OpenGL. We implemented crespucular rays, wave simulation, HDR and shadows.",
        cdesc: "使用Qt和OpenGL的实时渲染项目，包含体积光、水面模拟、HDR以及阴影。",
    },
    {
        id: "2022_4",
        name: "Fire~~~",
        cname: "森林火灾模拟器",
        time: ["2022-03", "2022-05"],
        tags: ["project"],
        img: i + "fire.png",
        link: "",
        desc: "We re-implemented the paper Fire in Paradise and added a few interaction functions. This project is based on OpenGL, Qt and CUDA. \
            The project can be found in https://github.com/herewegoblueno/team-wildfire.",
        cdesc: "我们重现了Fire in Paradise这篇文章中的内容，并添加了一些交互选项。",
    },
    {
        id: "2019_8",
        name: "French",
        cname: "法语",
        time: ["2018-12", "2020-05"],
        tags: ["skill"],
        img: i + "",
        link: "",
        desc: "Pas très bien...",
        cdesc: "差不多只会回答Oui/Non的水平吧...",
    },
    {
        id: "2019_11",
        name: "Navigation Testbed",
        cname: "传感器平台发表",
        time: ["2019-8", "2019-12"],
        tags: ["publication"],
        link: "https://ieeexplore.ieee.org/document/8702610",
        img: i + "testbed.png",
        desc: "ISCAS2019, Design of a reconfigurable multi-sensor testbed for autonomous vehicles and ground robots",
        cdesc: "ISCAS2019, Design of a reconfigurable multi-sensor testbed for autonomous vehicles and ground robots",
    },
    {
        id: "2020_5",
        name: "CooGAN",
        cname: "CooGAN",
        tags: ["publication"],
        time: ["2019-11", "2020-5"],
        img: i + "Coogan.png",
        link: "https://arxiv.org/abs/2011.01563",
        desc: "ECCV2020, CooGAN: A Memory-Efficient Framework for High-Resolution Facial Attribute Editing",
        cdesc: "ECCV2020, CooGAN: A Memory-Efficient Framework for High-Resolution Facial Attribute Editing",
    },
    {
        id: "2022_10",
        name: "SPDNet",
        cname: "SPDNet",
        tags: ["publication"],
        time: ["2019-11", "2020-5"],
        img: i + "spdnet.png",
        link: "",
        desc: "Accepted by NeulIPS2022, SPDNet: A Large-Scale Imagery Dataset and Benchmark for Spatial Precipitation Downscaling",
        cdesc: "Accepted by NeulIPS2022, SPDNet: A Large-Scale Imagery Dataset and Benchmark for Spatial Precipitation Downscalingg",
    },
    {
        id: "2021_5",
        name: "FOTAST",
        cname: "FOTAST",
        time: ["2021-3", "2021-6"],
        tags: ["publication"],
        img: i + "fost.png",
        link: "https://link.springer.com/chapter/10.1007/978-3-030-67832-6_4",
        desc: "MMM2021, Fast Optimal Transport Artistic Style Transfer",
        cdesc: "MMM2021, Fast Optimal Transport Artistic Style Transfer",
    },
    {
        id: "2020_6",
        name: "SJTU",
        cname: "上海交大",
        time: ["2016-8", "2020-06"],
        tags: ['degree'],
        link: "",
        img: i + "sjtu.jpg",
        desc: "B.S. in mechanical engineering and french literature.",
        cdesc: "机械工程试点班，工学学士；法语语言学，文学学士",
    },
    {
        id: "2021_4",
        name: "coffee trip",
        cname: "咖啡之旅",
        time: ["2021-04", "now"],
        tags: ["life"],
        img: i + "coffee.png",
        link: "",
        desc: "I've really grown to like coffee. Wish I could visit all interesting cafes in the world.",
        cdesc: "开始尝试世上各种咖啡",
    },
    {
        id: "2021_7",
        name: "Brown",
        cname: "布朗",
        time: ["2021-7", "now"],
        tags: ["degree"],
        img: i + "brown.jpg",
        link: "",
        desc: "Currently enrolled in CS PhD program at Brown University.",
        cdesc: "Pvd很偏远，但也挺好",
    },
    {
        id: "2022_7",
        name: "Guitar",
        cname: "吉他",
        time: ["2022-7", "now"],
        tags: ["life"],
        img: i + "guitar.jpg",
        link: "",
        desc: "Trying to be a fingerstyle guitarist.",
        cdesc: "我爱指弹",
    },
];